import type { Metadata } from "next";
import "./globals.css";
import { NextAuthProvider } from "./components/ClientProvider";
import { Toaster } from "sonner";

export const metadata: Metadata = {
   title: "Semako",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: {
   children: React.ReactNode;
}) {
   return (
      <NextAuthProvider>
         <html lang="en">
            <body className="font-sans">
               {children}
               <Toaster
                  richColors
                  toastOptions={{
                     style: {
                        background: "black",
                        color: "white",
                     },
                  }}
               />
            </body>
         </html>
      </NextAuthProvider>
   );
}
