import type { Metadata } from "next";
import "../globals.css";
import { MobileSideBar, Sidebar } from "../components";
import { Toaster } from "sonner";

export const metadata: Metadata = {
   title: "Dashboard | Semako",
   description: "Generated by create next app",
};

export default async function RootLayout({
   children,
}: {
   children: React.ReactNode;
}) {
   return (
      <html lang="en">
         <body>
            <div className="flex flex-row">
               <Sidebar />
               <MobileSideBar />
               {children}
               <Toaster
                  richColors
                  toastOptions={{
                     style: {
                        background: "black",
                        color: "white",
                     },
                  }}
               />
            </div>
         </body>
      </html>
   );
}
